name: buitrago
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#002985'
    - '#96bd11'
    - '#7597c3'
    - '#d0dbe9'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.18029551533982158
  rhythmicContrast: 0
purpose: []
